version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      astro:
        patterns:
          - "astro*"
          - "sharp"
        update-types:
          - "minor"
          - "patch"
      astro-adapters:
        patterns:
          - "@astrojs/cloudflare"
          - "@astrojs/react"
          - "@astrojs/tailwind"
        update-types:
          - "minor"
          - "patch"
      ai:
        patterns:
          - "@ai-sdk/openai"
          - "ai"
          - "openai"
        update-types:
          - "minor"
          - "patch"
      tailwind:
        patterns:
          - "@tailwindcss/*"
          - "class-variance-authority"
          - "clsx"
          - "tailwindcss"
          - "tailwindcss-animate"
          - "tailwind-merge"
        update-types:
          - "minor"
          - "patch"
      react:
        patterns:
          - "react*"
          - "lucide-react"
        update-types:
          - "minor"
          - "patch"
      components:
        patterns:
          - "@radix-ui/*"
          - "cmdk"
        update-types:
          - "minor"
          - "patch"
      development:
        patterns:
          - "@astrojs/check"
          - "@types/*"
          - "prettier*"
          - "type-coverage"
          - "typescript"
          - "wrangler"
        update-types:
          - "minor"
          - "patch"
      misc:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"