version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      astro:
        patterns:
          - "astro*"
          - "@astrojs/check"
          - "sharp"
        update-types:
          - "minor"
          - "patch"
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
          - "@astrojs/tailwind"
          - "clsx"
          - "tailwind-merge"
          - "tailwindcss-animate"
          - "class-variance-authority"
        update-types:
          - "minor"
          - "patch"
      prettier:
        patterns:
          - "prettier*"
        update-types:
          - "minor"
          - "patch"
      react:
        patterns:
          - "@astrojs/react"
          - "@types/react-dom"
          - "@types/react"
          - "lucide-react"
        update-types:
          - "minor"
          - "patch"
      components:
        patterns:
          - "@radix-ui/*"
          - "cmdk"
        update-types:
          - "minor"
          - "patch"
      misc:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"