tabWidth: 2
semi: true
bracketSameLine: true
printWidth: 80
singleQuote: true
jsxSingleQuote: false
trailingComma: "es5"
tailwindAttributes:
  - Classes
  - buttonStyles
  - iconStyles
tailwindFunctions:
  - cn
  - clsx
  - cva
  - tw

plugins:
  - "prettier-plugin-astro"
  - "prettier-plugin-tailwindcss"